{
  imports = [
    ./browser
    ./discord.nix
    ./dankMaterialShell
    ./easyeffects.nix
    ./ghostty.nix
    ./gzdoom.nix
    ./heroic
    ./lutris.nix
    ./mpv.nix
    ./niri-conf.nix
    ./obs
    ./obsidian.nix
    ./prism-launcher.nix
    ./qt
    ./virt-manager.nix
    ./fastfetch
    ./signal.nix
    ./spicetify.nix
    ./nextcloud-client
    ./steam-rom-manager.nix
    ./ytmusic.nix
    ./zed.nix
  ];
}
